name: Build and deploy TBRBot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

      - name: Install dependencies
        run: go mod download

      - name: Build it
        run: go build
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./ToBeReviewedBot
  
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [build]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Import SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List artifacts
        run: ls

      - name: Test SSH connectivity
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_INSTANCE }} 'echo Success'

      - name: Upload binary to server
        run: scp -o StrictHostKeyChecking=no ToBeReviewedBot ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_INSTANCE }}:~

      - name: Move binary to service folder
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_INSTANCE }} 'sudo cp ~/ToBeReviewedBot /usr/local/lib/tbrbot/tbrbot'

      - name: Chown binary
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_INSTANCE }} 'sudo chown app:app /usr/local/lib/tbrbot/tbrbot'

      - name: Restart systemd unit
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_INSTANCE }} 'sudo systemctl restart tbrbot'
