name: Build and deploy TBRBot
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

      - name: Install dependencies
        run: go mod download

      - name: Build it
        run: go build
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./ToBeReviewedBot
  
        
